# Generated by Django 6.0.4 on 2026-05-01 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("ano_lancamento", models.IntegerField()),
                ("thumb", models.ImageField(upload_to="thumbs/")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ANÁLISE", "Análise"),
                            ("CURSOS LIXO", "Cursos Lixo"),
                            ("CURSOS TOPS", "Cursos Tops"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "datalancamento",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
